#!/bin/sh
# 向 obs-record 插件发送控制命令。
# 用法: obs-record-cli zoom toggle
#       OBS_RECORD_SOCKET=/path/to.sock obs-record-cli pin add
exec python3 -c '
import socket, sys
s = socket.socket(socket.AF_UNIX)
s.connect(sys.argv[1])
s.sendall((" ".join(sys.argv[2:]) + "\n").encode())
s.close()
' "${OBS_RECORD_SOCKET:-$XDG_RUNTIME_DIR/obs-record.sock}" "$@"
